components:
  schemas:
    AuthenticateRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      example:
        username: test@gmail.com
        password: Testing1*
    ChangePasswordRequest:
      type: object
      properties:
        username:
          type: string
        currentPassword:
          type: string
        newPassword:
          type: string
      example:
        username: test@gmail.com
        currentPassword: Testing1*
        newPassword: Testing2*
    CreateAccountRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      example:
        username: test@gmail.com
        password: Testing1*
    DeleteAccountRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      example:
        username: test@gmail.com
        password: Testing1*
    ForgotPasswordRequest:
      type: object
      properties:
        username:
          type: string
      example:
        username: test@gmail.com
    SetPasswordRequest:
      type: object
      properties:
        token:
          type: string
        newPassword:
          type: string
      example:
        token: token
        newPassword: Testing2*